version: "3.8"

services:
  backend:
    build: .
    command: npm run start
    volumes:
      - .:/usr/app
    ports:
      - 3000:3000
    links:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: rov
    # volumes:
    #   - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
   